server:
  port: 4001
spring:
  application:
    name: service-a
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.61.216.123:13306/txlcn-demo?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=true
    username: root
    password: root
    hikari:
      maximum-pool-size: 20
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  configuration:
    map-underscore-to-camel-case: true